// src/app/mock-data.ts

export const getlocation = [
  { locationId: 1, locationName: 'Mumbai' },
  { locationId: 2, locationName: 'Delhi' },
  { locationId: 3, locationName: 'Bangalore' },
  { locationId: 4, locationName: 'Chennai' },
  { locationId: 5, locationName: 'Kolkata' },
  { locationId: 6, locationName: 'Pune' },
  { locationId: 7, locationName: 'Hyderabad' }
];

export const searchbuses = [
  {
    busId: 1,
    busName: 'Volvo Express',
    busType: 'AC Seater',
    fromLocationId: 1,
    fromLocation: 'Mumbai',
    toLocationId: 2,
    toLocation: 'Delhi',
    travelDate: '2026-01-30',
    departureTime: '10:00 AM',
    arrivalTime: '02:00 AM',
    duration: '16 hr',
    price: 1200,
    availableSeats: 25,
    totalSeats: 40,
    rating: 4.5,
    ratingsCount: 567
  },
  {
    busId: 2,
    busName: 'Sleeper Coach',
    busType: 'AC Sleeper',
    fromLocationId: 1,
    fromLocation: 'Mumbai',
    toLocationId: 2,
    toLocation: 'Delhi',
    travelDate: '2026-01-30',
    departureTime: '08:00 PM',
    arrivalTime: '12:00 PM',
    duration: '16 hr',
    price: 950,
    availableSeats: 15,
    totalSeats: 40,
    rating: 4.2,
    ratingsCount: 342
  },
  {
    busId: 3,
    busName: 'Royal Express',
    busType: 'Non-AC Seater',
    fromLocationId: 3,
    fromLocation: 'Bangalore',
    toLocationId: 4,
    toLocation: 'Chennai',
    travelDate: '2026-01-31',
    departureTime: '06:00 AM',
    arrivalTime: '10:00 PM',
    duration: '16 hr',
    price: 750,
    availableSeats: 30,
    totalSeats: 45,
    rating: 3.9,
    ratingsCount: 228
  },
  {
    busId: 4,
    busName: 'CityLink Volvo',
    busType: 'AC Seater',
    fromLocationId: 5,
    fromLocation: 'Kolkata',
    toLocationId: 2,
    toLocation: 'Delhi',
    travelDate: '2026-01-31',
    departureTime: '09:00 AM',
    arrivalTime: '09:00 PM',
    duration: '12 hr',
    price: 1300,
    availableSeats: 20,
    totalSeats: 40,
    rating: 4.6,
    ratingsCount: 198
  },
  {
    busId: 5,
    busName: 'Night Rider',
    busType: 'AC Sleeper',
    fromLocationId: 6,
    fromLocation: 'Pune',
    toLocationId: 1,
    toLocation: 'Mumbai',
    travelDate: '2026-01-30',
    departureTime: '11:00 PM',
    arrivalTime: '04:00 AM',
    duration: '5 hr',
    price: 500,
    availableSeats: 10,
    totalSeats: 30,
    rating: 4.0,
    ratingsCount: 112
  },
  {
    busId: 6,
    busName: 'Hyderabad Express',
    busType: 'Non-AC Seater',
    fromLocationId: 7,
    fromLocation: 'Hyderabad',
    toLocationId: 3,
    toLocation: 'Bangalore',
    travelDate: '2026-02-01',
    departureTime: '07:00 AM',
    arrivalTime: '03:00 PM',
    duration: '8 hr',
    price: 650,
    availableSeats: 18,
    totalSeats: 35,
    rating: 3.8,
    ratingsCount: 75
  },
  {
    busId: 7,
    busName: 'Super Sleeper',
    busType: 'AC Sleeper',
    fromLocationId: 2,
    fromLocation: 'Delhi',
    toLocationId: 5,
    toLocation: 'Kolkata',
    travelDate: '2026-02-02',
    departureTime: '06:00 PM',
    arrivalTime: '06:00 AM',
    duration: '12 hr',
    price: 1100,
    availableSeats: 22,
    totalSeats: 40,
    rating: 4.3,
    ratingsCount: 300
  },
  {
    busId: 8,
    busName: 'Pune Deluxe',
    busType: 'AC Seater',
    fromLocationId: 6,
    fromLocation: 'Pune',
    toLocationId: 1,
    toLocation: 'Mumbai',
    travelDate: '2026-02-01',
    departureTime: '08:30 AM',
    arrivalTime: '01:30 PM',
    duration: '5 hr',
    price: 550,
    availableSeats: 25,
    totalSeats: 35,
    rating: 4.1,
    ratingsCount: 90
  },
  // 10 more entries
  {
    busId: 9,
    busName: 'Express Comfort',
    busType: 'AC Seater',
    fromLocationId: 1,
    fromLocation: 'Mumbai',
    toLocationId: 3,
    toLocation: 'Bangalore',
    travelDate: '2026-02-02',
    departureTime: '07:00 AM',
    arrivalTime: '09:00 PM',
    duration: '14 hr',
    price: 1400,
    availableSeats: 18,
    totalSeats: 40,
    rating: 4.4,
    ratingsCount: 210
  },
  {
    busId: 10,
    busName: 'Chennai Sleeper',
    busType: 'AC Sleeper',
    fromLocationId: 4,
    fromLocation: 'Chennai',
    toLocationId: 2,
    toLocation: 'Delhi',
    travelDate: '2026-02-03',
    departureTime: '09:00 PM',
    arrivalTime: '09:00 AM',
    duration: '12 hr',
    price: 1250,
    availableSeats: 20,
    totalSeats: 35,
    rating: 4.2,
    ratingsCount: 150
  },
  {
    busId: 11,
    busName: 'Kolkata Nightliner',
    busType: 'AC Sleeper',
    fromLocationId: 5,
    fromLocation: 'Kolkata',
    toLocationId: 7,
    toLocation: 'Hyderabad',
    travelDate: '2026-02-04',
    departureTime: '10:00 PM',
    arrivalTime: '10:00 AM',
    duration: '12 hr',
    price: 1150,
    availableSeats: 15,
    totalSeats: 40,
    rating: 4.1,
    ratingsCount: 130
  },
  {
    busId: 12,
    busName: 'Bangalore AC Deluxe',
    busType: 'AC Seater',
    fromLocationId: 3,
    fromLocation: 'Bangalore',
    toLocationId: 1,
    toLocation: 'Mumbai',
    travelDate: '2026-02-05',
    departureTime: '06:00 AM',
    arrivalTime: '08:00 PM',
    duration: '14 hr',
    price: 1350,
    availableSeats: 12,
    totalSeats: 40,
    rating: 4.3,
    ratingsCount: 180
  },
  {
    busId: 13,
    busName: 'Delhi SuperFast',
    busType: 'Non-AC Seater',
    fromLocationId: 2,
    fromLocation: 'Delhi',
    toLocationId: 6,
    toLocation: 'Pune',
    travelDate: '2026-02-03',
    departureTime: '07:00 AM',
    arrivalTime: '07:00 PM',
    duration: '12 hr',
    price: 900,
    availableSeats: 20,
    totalSeats: 35,
    rating: 3.9,
    ratingsCount: 110
  },
  {
    busId: 14,
    busName: 'Hyderabad Night Express',
    busType: 'AC Sleeper',
    fromLocationId: 7,
    fromLocation: 'Hyderabad',
    toLocationId: 2,
    toLocation: 'Delhi',
    travelDate: '2026-02-06',
    departureTime: '09:00 PM',
    arrivalTime: '09:00 AM',
    duration: '12 hr',
    price: 1200,
    availableSeats: 18,
    totalSeats: 40,
    rating: 4.5,
    ratingsCount: 200
  },
  {
    busId: 15,
    busName: 'Pune Express',
    busType: 'AC Seater',
    fromLocationId: 6,
    fromLocation: 'Pune',
    toLocationId: 4,
    toLocation: 'Chennai',
    travelDate: '2026-02-07',
    departureTime: '06:00 AM',
    arrivalTime: '06:00 PM',
    duration: '12 hr',
    price: 1250,
    availableSeats: 22,
    totalSeats: 40,
    rating: 4.2,
    ratingsCount: 145
  },
  {
    busId: 16,
    busName: 'Mumbai Nightliner',
    busType: 'Non-AC Seater',
    fromLocationId: 1,
    fromLocation: 'Mumbai',
    toLocationId: 5,
    toLocation: 'Kolkata',
    travelDate: '2026-02-08',
    departureTime: '10:00 PM',
    arrivalTime: '10:00 AM',
    duration: '12 hr',
    price: 950,
    availableSeats: 10,
    totalSeats: 40,
    rating: 3.8,
    ratingsCount: 100
  },
  {
    busId: 17,
    busName: 'Chennai Comfort',
    busType: 'AC Seater',
    fromLocationId: 4,
    fromLocation: 'Chennai',
    toLocationId: 3,
    toLocation: 'Bangalore',
    travelDate: '2026-02-08',
    departureTime: '08:00 AM',
    arrivalTime: '04:00 PM',
    duration: '8 hr',
    price: 800,
    availableSeats: 28,
    totalSeats: 35,
    rating: 4.0,
    ratingsCount: 90
  },
  {
    busId: 18,
    busName: 'Delhi Sleeper',
    busType: 'AC Sleeper',
    fromLocationId: 2,
    fromLocation: 'Delhi',
    toLocationId: 1,
    toLocation: 'Mumbai',
    travelDate: '2026-02-09',
    departureTime: '09:00 PM',
    arrivalTime: '09:00 AM',
    duration: '12 hr',
    price: 1150,
    availableSeats: 20,
    totalSeats: 40,
    rating: 4.3,
    ratingsCount: 160
  }
  // ... rest of your buses
];
